USE recency_uganda_prod_analysis_test;
GO

-- $BEGIN

EXEC derived_recency.sp_fact_recency_surveillance_create;
-- EXEC derived_recency.sp_fact_recency_surveillance_insert_hts_with_uvri;
EXEC derived_recency.sp_fact_recency_surveillance_insert_hts_without_uvri;
-- EXEC derived_recency.sp_fact_recency_surveillance_insert_uvri_without_hts;
EXEC derived_recency.sp_fact_recency_surveillance_cleaning;
EXEC derived_recency.sp_fact_recency_surveillance_update_derived_fields;
EXEC derived_recency.sp_fact_recency_surveillance_trim_date_dimensions;

-- $END