USE recency_uganda_prod_analysis_test
GO

DROP TABLE IF EXISTS base.fact_cqi_assessment_merged;

-- $BEGIN

CREATE TABLE base.fact_cqi_assessment_merged (
    cqi_assessment_merged_id UNIQUEIDENTIFIER NOT NULL,
    form_version VARCHAR(2) NOT NULL,
    uri NVARCHAR(255) NOT NULL,
    cqi_checklist_type NVARCHAR(255) NULL,
    assessment_point NVARCHAR(255) NULL,
    visit_date DATE NOT NULL,
    visit_date_id INT NOT NULL,
    review_period_start_date DATE NOT NULL,
    review_period_start_date_id INT NOT NULL,
    review_period_end_date DATE NOT NULL,
    review_period_end_date_id INT NOT NULL,
    visitor_name NVARCHAR(255) NULL,
    visitor_name_other NVARCHAR(255) NULL,
    ss_total_hts_providers INT NULL,
    ss_number_of_hts_providers_trained INT NULL,
    ss_hts_providers_trained_comments NVARCHAR(255) NULL,
    ss_number_of_hts_providers_trained_available INT NULL,
    ss_number_of_hts_providers_trained_working INT NULL,
    ss_number_of_hts_providers_trained_by_cme INT NULL,
    ss_hts_providers_follow_sops_for_eligibility TINYINT NULL,
    ss_hts_providers_follow_sops_for_eligibilit_comment NVARCHAR(255) NULL,
    ss_hts_providers_follow_sops_for_testing TINYINT NULL,
    ss_hts_providers_follow_sops_for_testing_comment NVARCHAR(255) NULL,
    ss_hts_providers_interpret_results_accurately INT NULL,
    ss_hts_providers_interpret_results_accurately_comment NVARCHAR(255) NULL,
    ss_all_tests_with_control_and_verification_line_marked_recent TINYINT NULL,
    ss_all_tests_with_control_and_verification_line_marked_recent_comment NVARCHAR(255) NULL,
    ss_all_tests_with_three_lines_marked_long_term TINYINT NULL,
    ss_all_tests_with_three_lines_marked_long_term_comment NVARCHAR(255) NULL,
    ss_all_tests_with_only_control_line_marked_negative TINYINT NULL,
    ss_all_tests_with_only_control_line_marked_negative_comment NVARCHAR(255) NULL,
    ss_all_invalid_tests_interpreted_correctly TINYINT NULL,
    ss_all_invalid_tests_interpreted_correctly_comment NVARCHAR(255) NULL,
    ss_docs_showing_all_hts_providers_trained_in_routine_rapid_testing TINYINT NULL,
    ss_docs_showing_all_hts_providers_trained_in_routine_rapid_testing_comment NVARCHAR(255) NULL,
    ss_docs_showing_all_hts_providers_trained_in_rtri_testing TINYINT NULL,
    ss_docs_showing_all_hts_providers_trained_in_rtri_testing_comment NVARCHAR(255) NULL,
    ss_hts_performed_in_private_space TINYINT NULL,
    ss_hts_performed_in_private_space_comment NVARCHAR(255) NULL,
    ss_any_recency_trained_staff_changes_since_training INT NULL,
    ss_any_recency_trained_staff_changes_since_training_comment NVARCHAR(255) NULL,
    ss_score_denominator NVARCHAR(255) NULL,
    ss_score NVARCHAR(255) NULL,
    procedures_sop_manual_visible_at_facility_location TINYINT NULL,
    procedures_sop_manual_visible_at_facility_location_comment NVARCHAR(255) NULL,
    procedures_informed_consent_materials_easily_physically_accessible TINYINT NULL,
    procedures_informed_consent_materials_easily_physically_accessible_comment NVARCHAR(255) NULL,
    procedures_rtri_conducted_correctly TINYINT NULL,
    procedures_rtri_conducted_correctly_comment NVARCHAR(255) NULL,
    procedures_sample_buffer_tube_labeled_with_client_identifiers TINYINT NULL,
    procedures_sample_buffer_tube_labeled_with_client_identifiers_comment NVARCHAR(255) NULL,
    procedures_timers_available_and_used_routinely_for_rtri TINYINT NULL,
    procedures_timers_available_and_used_routinely_for_rtri_comment NVARCHAR(255) NULL,
    procedures_sop_followed_for_rtri TINYINT NULL,
    procedures_sop_followed_for_rtri_comment NVARCHAR(255) NULL,
    procedures_repeat_testing_of_invalid_tests_done TINYINT NULL,
    procedures_repeat_testing_of_invalid_tests_done_comment NVARCHAR(255) NULL,
    procedures_specimen_collection_timely TINYINT NULL,
    procedures_specimen_collection_timely_comment NVARCHAR(255) NULL,
    procedures_qc_for_positive_and_negative_routinely_used TINYINT NULL,
    procedures_qc_for_positive_and_negative_routinely_used_comment NVARCHAR(255) NULL,
    procedures_recency_pt_performed_by_hts_providers TINYINT NULL,
    procedures_recency_pt_performed_by_hts_providers_comment NVARCHAR(255) NULL,
    procedures_samples_prepared_according_to_schedule TINYINT NULL,
    procedures_samples_prepared_according_to_schedule_comment NVARCHAR(255) NULL,
    procedures_electronic_data_entry_done_weekly TINYINT NULL,
    procedures_electronic_data_entry_done_weekly_comment NVARCHAR(255) NULL,
    procedures_corrective_action_taken_in_sop_failure_taken TINYINT NULL,
    procedures_corrective_action_taken_in_sop_failure_taken_comment NVARCHAR(255) NULL,
    procedures_date_of_qc DATE NULL,
    procedures_kit_lot_number NVARCHAR(255) NULL,
    procedures_score_denominator INT NULL,
    procedures_score NVARCHAR(255) NULL,
    sd_number_records_in_logbook INT NULL,
    sd_number_records_in_logbook_comment NVARCHAR(255) NULL,
    sd_number_records_in_logbook_rtri_complete INT NULL,
    sd_number_records_in_logbook_rtri_complete_comment NVARCHAR(255) NULL,
    sd_number_records_with_complete_hts_id INT NULL,
    sd_number_records_with_complete_hts_id_comment NVARCHAR(255) NULL,
    sd_number_records_in_logbook_with_complete_kit_details INT NULL,
    sd_number_records_in_logbook_with_complete_kit_details_comment NVARCHAR(255) NULL,
    sd_total_specimen_shipment_forms_created INT NULL,
    sd_total_specimen_shipment_forms_created_comment NVARCHAR(255) NULL,
    sd_total_specimens_in_shipment_forms INT NULL,
    sd_total_specimens_in_shipment_forms_comment NVARCHAR(255) NULL,
    sd_total_specimens_in_shipment_forms_completely_filled INT NULL,
    sd_total_specimens_in_shipment_forms_completely_filled_comment NVARCHAR(255) NULL,
    sd_only_standard_hts_forms_used TINYINT NULL,
    sd_only_standard_hts_forms_used_comment NVARCHAR(255) NULL,
    sd_hts_forms_correctly_filled INT NULL,
    sd_hts_forms_correctly_filled_comment NVARCHAR(255) NULL,
    sd_all_hts_register_demographics_and_rtri_results_correctly_filled TINYINT NULL,
    sd_all_hts_register_demographics_and_rtri_results_correctly_filled_comment NVARCHAR(255) NULL,
    sd_all_logbooks_correctly_filled_with_kit_details_and_rtri_results TINYINT NULL,
    sd_all_logbooks_correctly_filled_with_kit_details_and_rtri_results_comment NVARCHAR(255) NULL,
    sd_all_records_in_hts_register_have_hts_history TINYINT NULL,
    sd_all_records_in_hts_register_have_hts_history_comment NVARCHAR(255) NULL,
    sd_all_records_in_hts_register_have_final_hts_diagnosis TINYINT NULL,
    sd_all_records_in_hts_register_have_final_hts_diagnosis_comment NVARCHAR(255) NULL,
    [sd_prop_of_records_complete_with_hts_id] DECIMAL(10,4) NULL,
    [sd_prop_of_samples_shipped_to_hub] DECIMAL(10,4) NULL,
    sd_score_denominator NVARCHAR(255) NULL,
    sd_score NVARCHAR(255) NULL,
    pf_sufficient_lighting_in_testing_area TINYINT NULL,
    pf_sufficient_lighting_in_testing_area_comment NVARCHAR(255) NULL,
    pf_kits_stored_according_to_instructions TINYINT NULL,
    pf_kits_stored_according_to_instructions_comment NVARCHAR(255) NULL,
    pf_current_and_past_temperature_charts_available TINYINT NULL,
    pf_current_and_past_temperature_charts_available_comment NVARCHAR(255) NULL,
    pf_records_stored_in_secure_storage_room TINYINT NULL,
    pf_records_stored_in_secure_storage_room_comment NVARCHAR(255) NULL,
    pf_all_electronic_tools_password_protected TINYINT NULL,
    pf_all_electronic_tools_password_protected_comment NVARCHAR(255) NULL,
    pf_score_denominator NVARCHAR(255) NULL,
    pf_score NVARCHAR(255) NULL,
    prf_total_15_and_above_received_hts INT NULL,
    prf_total_15_and_above_received_hts_comment NVARCHAR(255) NULL,
    prf_total_clients_eligible INT NULL,
    prf_total_clients_eligible_comment NVARCHAR(255) NULL,
    prf_total_clients_enrolled_for_rtri INT NULL,
    prf_total_clients_enrolled_for_rtri_comment NVARCHAR(255) NULL,
    prf_total_clients_ineligible INT NULL,
    prf_total_clients_ineligible_comment NVARCHAR(255) NULL,
    prf_total_clients_enrolled_for_rtri_with_correct_consent_doc INT NULL,
    prf_total_clients_enrolled_for_rtri_with_correct_consent_doc_comment NVARCHAR(255) NULL,
    prf_total_15_and_above_tested_recent INT NULL,
    prf_total_15_and_above_tested_recent_comment NVARCHAR(255) NULL,
    prf_total_15_and_above_tested_long_term INT NULL,
    prf_total_15_and_above_tested_long_term_comment NVARCHAR(255) NULL,
    prf_total_clients_enrolled_for_rtri_repoering_adverse_events INT NULL,
    prf_total_clients_enrolled_for_rtri_repoering_adverse_events_comment NVARCHAR(255) NULL,
    prf_score_denominator NVARCHAR(255) NULL,
    prf_score NVARCHAR(255) NULL,
    site_supplies_asante_test_kits_available INT NULL,
    site_supplies_asante_test_kits_available_comment NVARCHAR(255) NULL,
    site_supplies_specimen_shipment_forms_available INT NULL,
    site_supplies_specimen_shipment_forms_available_comment NVARCHAR(255) NULL,
    site_supplies_samples_shipped INT NULL,
    site_supplies_samples_shipped_comment NVARCHAR(255) NULL,
    site_supplies_samples_shipped_rejected INT NULL,
    site_supplies_samples_shipped_rejected_comment NVARCHAR(255) NULL,
    site_supplies_logbooks_available INT NULL,
    site_supplies_logbooks_available_comment NVARCHAR(255) NULL,
    site_supplies_all_rtri_supplies_available TINYINT NULL,
    site_supplies_all_rtri_supplies_available_comment NVARCHAR(255) NULL,
    site_supplies_asante_test_kits_available_and_stocked TINYINT NULL,
    site_supplies_asante_test_kits_available_and_stocked_comment NVARCHAR(255) NULL,
    site_supplies_ppt_edta_tubes_available TINYINT NULL,
    site_supplies_ppt_edta_tubes_available_comment NVARCHAR(255) NULL,
    site_supplies_rtri_supplies_used_before_expiry TINYINT NULL,
    site_supplies_rtri_supplies_used_before_expiry_comment NVARCHAR(255) NULL,
    site_supplies_score_denominator NVARCHAR(255) NULL,
    site_supplies_score NVARCHAR(255) NULL,
    visit_number INT NULL,
    reversed_visit_number INT NULL,
    is_latest_visit TINYINT NULL,
    ss_prop_of_trained_hts_providers DECIMAL(10,4) NULL,
    ss_prop_of_trained_hts_providers_available_during_visit DECIMAL(10,4) NULL,
    ss_prop_of_hts_providers_trained_on_hiv_rapid_testing DECIMAL(10,4) NULL,
    cx_study_staff_score DECIMAL(10,4) NULL,
    cx_procedures_score DECIMAL(10,4) NULL,
    sd_prop_of_complete_records_in_logbook DECIMAL(10,4) NULL,
    sd_prop_of_complete_records_with_kit_details DECIMAL(10,4) NULL,
    sd_prop_of_shipment_forms_completely_filled DECIMAL(10,4) NULL,
    cx_source_data_score DECIMAL(10,4) NULL,
    cx_physical_facility_score DECIMAL(10,4) NULL,
    prf_prop_of_enrolled_clients_in_rtri DECIMAL(10,4) NULL,
    prf_prop_of_enrolled_clients_in_rtri_with_consent_doc DECIMAL(10,4) NULL,
    cx_participant_recruitment_score DECIMAL(10,4) NULL,
    cx_site_supplies_score DECIMAL(10,4) NULL,
  	facility_id UNIQUEIDENTIFIER NULL
);

ALTER TABLE base.fact_cqi_assessment_merged ADD CONSTRAINT PK_cqi_assessment_merged PRIMARY KEY (cqi_assessment_merged_id);

ALTER TABLE base.fact_cqi_assessment_merged  ADD 
CONSTRAINT FK_merged_assessment_facility
FOREIGN KEY (facility_id) REFERENCES base.dim_facility (facility_id);

ALTER TABLE base.fact_cqi_assessment_merged ADD 
CONSTRAINT FK_merged_assessment_visit_date
FOREIGN KEY (visit_date_id) REFERENCES base.dim_date (date_id);


ALTER TABLE base.fact_cqi_assessment_merged ADD 
CONSTRAINT FK_merged_assessment_review_period_start_date 
FOREIGN KEY (review_period_start_date_id) REFERENCES base.dim_date (date_id);

ALTER TABLE base.fact_cqi_assessment_merged ADD 
CONSTRAINT FK_merged_assessment_review_period_end_date 
FOREIGN KEY (review_period_end_date_id) REFERENCES base.dim_date (date_id)

-- $END