-- Temporary view creation for Postgres (will be changed when analysis server is back)
CREATE OR REPLACE VIEW  vw_odk_fom_shortened_cqi_checklist AS 
SELECT 
    "meta_instanceID" AS _uri,
    "start" AS form_start_time,
    "end" AS form_end_time,
    "visit_date" AS form_date,
    "region",
    "district",
    "site" AS facility_id,
    "entry_point",
    "entry_point_other",
    "review_group_visit_date_2" AS date_of_contact,
    "review_group_review_period_start" AS review_period_start_date,
    "review_group_review_period_end" AS review_period_end_date,
    "review_group_visitor_name" AS visitor_name,
    "review_group_visitor_name_other" AS visitor_name_other,
    "hts_provider_group_number_provider_available_at_point" AS number_of_hts_providers_available,
    "hts_provider_group_number_provider_missing" AS number_of_hts_providers_available_missing,
    "hts_provider_trained_group_number_provider_tot_trained" AS number_of_hts_providers_trained,
    "hts_provider_trained_group_number_provider_trained_missing" AS number_of_hts_providers_trained_missing,
    "number_hts_provider_not_tot_trained" AS number_of_hts_providers_not_trained,
    "number_hts_provider_not_tot_trained1" AS number_of_hts_providers_not_trained_missing,
    "staff_changes_group_provider_obs_staffing_changes" has_staff_changed,
    "staff_changes_group_provider_obs_staffing_changes_comment" staff_changes_comment,
    "procedures_obs_data_electronic" AS is_electronic_data_entry_occuring_weekly,
    "procedures_obs_qc_performed" AS is_qc_routinely_performed_per_guidelines,
    "date_last_QC_performed" AS date_of_last_qc_performed,
    "kit_lot_mumber",
    "recent_eligible_group_recent_eligible" AS number_of_eligible_clients,
    "recent_eligible_group_recent_eligible_missing" AS number_of_eligible_clients_missing,
    "participant_recruitment_recent_enrolled" AS number_of_enrolled_clients,
    "participant_recruitment_recent_tested_missing" AS number_of_enrolled_clients_missing,
    "participant_recruitment_recent_ineligible" AS number_of_ineligible_clients,
    "participant_recruitment_recent_ineligible_missing" AS number_of_ineligible_clients_missing,
    "participant_recruitment_recent_tested_pos" AS number_of_clients_tested_positive,
    "participant_recruitment_recent_tested_pos_missing" AS number_of_clients_tested_positive_missing,
    "participant_recruitment_long_term_tested" AS number_of_clients_tested_long_term,
    "participant_recruitment_long_term_tested_missing" AS number_of_clients_tested_long_term_missing,
    "specimen_shipment_group_specimen_shipment" AS number_of_specimens_shipped,
    "specimen_shipment_group_specimen_shipment_missing" AS number_of_specimens_shipped_missing,
    "asante_kits_group_supplies_tests_facility" AS number_of_asante_test_kits_available,
    "asante_kits_group_supplies_tests_facility_missing" AS number_of_asante_test_kits_available_missing,
    "available_required_supplies" is_all_required_supplies_available,
    "available_required_supplies_no" AS missing_supplies_notes,
    'v1' AS form_version
FROM 
    shortened_cqi_checklist_20200616